### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by ScribbleGhost** [Bananaman/BananaScripts#2]
Hello.

I just came across this script which was sorely needed. 😂
I am am just a little familiar with Python and I am having problems getting it to run on a Windows 10 computer.

```
C:\>mkvextract-allsubs.py video.mkv
Traceback (most recent call last):
  File "C:\mkvextract-allsubs.py", line 23, in <module>
    if not has_command(cmd):
  File "C:\mkvextract-allsubs.py", line 16, in has_command
    result = subprocess.run(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\>
```

I am running Python 3.10.6.
Please advise.

**Comment by ScribbleGhost** [comment]
It seems to be working if I removed these lines from the script:

```
for cmd in ["mkvmerge", "mkvextract"]:
    if not has_command(cmd):
        print(f"Missing dependency: {cmd}")
        exit(1)
```

I am using CMD and I have mkvmerge/mkvextract added to PATH.

**Comment by Arcitec** [comment]
@ScribbleGhost Hey, I really appreciate the detailed report! Unfortunately I didn't see it until today.

You helped pinpoint what's going on with Windows. I wrote this on Linux without any thoughts about Windows compatibility, but it was fairly trivial to add support for Windows today.

Version 1.1 is out now with built-in support for detecting the tools on Windows, along with some more instructions in the comments to help Windows users install the required dependencies. Thanks for helping make the tool better for everyone! :)
